### ISSUE TITLE
The issue about training hybrid stage.

### ISSUE THREAD

**Issue by lingtengqiu** [yfeng95/SCARF#4]
Thanks for your great work.

When I train the hybrid stage, the losses become Nan, as following grpah illustrates.
![图片](https://user-images.githubusercontent.com/37240099/211862865-b9728f83-34aa-4f43-a0bd-70985be432f2.png)

And also, the process of optimization is very slow(200 steps about 30 minutes.)

**Comment by SeungJunnn** [comment]
Same issue.

**Comment by lingtengqiu** [comment]
> Same issue.
I test the code in V100, it can work well while the loss will be nan in other devices(e.g., 30xx, A100)

**Comment by SeungJunnn** [comment]
Currently, I only have 3090 devices, so I cannot test it on V100. What might be the reason for that? I am curious about what makes the code to be worked device-dependently.

**Comment by SeungJunnn** [comment]
I tried to run my code excluding `IDMRFLoss`, and I saw no more NaN terms. But I am not sure whether the training is done in the advisable ways or not.

**Comment by lingtengqiu** [comment]
> I ran my code excluding `IDMRFLoss`, and I saw no more NaN terms. But I am not sure whether the training is done in the advisable ways or not. Also, I found that the optimization step becomes way faster with the temporary solution above.

I ask the author, she told me you can try to use perceptual loss instead of MSR loss on the 3090/A100 devices.  It may work.

**Comment by surheaven** [comment]
I use perceptual loss instead of MSR loss on the 3090 device, but the losses are all nan.
![image](https://github.com/yfeng95/SCARF/assets/89247297/da058514-18d1-4ba5-9c8e-7d0564fd9336)

**Comment by surheaven** [comment]
> IDMRFLoss
after excluding IDMRFLoss, it also nan in the hybrid. I dont know how to solve it. And the result like this,is it normal?
![image](https://github.com/yfeng95/SCARF/assets/89247297/0415e787-d3b9-4545-8ae1-f6dd7335fa8c)
