### ISSUE TITLE
How can we obtain 'full_pose' parameter in 'pixie_radioactive.pkl'?

### ISSUE THREAD

**Issue by SeungJunnn** [yfeng95/SCARF#8]
Hello. First of all, thank you for revealing your awesome works with open source.

I am curious how can we obtain 'full_pose' parameter, which consists of 55*3*3 size tensor per frame, in your given demo pose file 'pixie_radioactive.pkl'.

I think this can be driven by PIXIE, but I don't know how can we get it.

PIXIE parameters from the preprocessing have different shapes compared to the given one.

Thank you.

**Comment by SeungJunnn** [comment]
I got the answer from the code smplx.py.

Thank you.

**Comment by justinvo277** [comment]
@seungjun-moon 
I have the same question as you, I'm not sure how to get body_mesh and include "full_pose", "exp" and "albedo". I think it's some kind of file, do you know?
![image](https://github.com/user-attachments/assets/88763d70-9aee-4178-b059-79f13efebaa2)
